### PR TITLE
Completely removes Felinid from code

### PR DESCRIPTION
**Pull request by Jolly-66**
Tajarans are the better cat people anyway.

Completely removes most Felinid stuff, leaving behind ears, tails and hopefully the DNA infuser shenanigans. 
Some Felinid behavior has been given to the Tajarans.

## Changelog

:cl: Jolly
del: Felinids have been fully removed from code.
add: Some Felinid traits have been moved to Tajarans instead. These may or may not be removed at a later date.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
THE DECATTENING

**Comment by Jolly-66** [comment]
Need to figure out why the DNA infuser renders the tails invisible.

**Comment by Jolly-66** [comment]
Self reminder before this gets merged: Update config on the box.

**Comment by prodirus** [comment]
fuggit looks good enough for now we'll do it live

**Pull request merged**
