### PR TITLE
Tweaks and fixes a resource cache goodie grate

### PR DESCRIPTION
**Pull request by Jolly-66**
I don't know why this crate was triggering the crates, but if it does trigger the unit test again later I'll tweak the code further.

Also, it no longer runs up to 4 times, which I think was the major issue.

Fixes: #9517
Fixes: #9224
Fixes: #9213
Fixes: #9136
Fixes: #9121
Fixes: #9049
Fixes: #8782
Fixes: #8726
Fixes: #8723
Fixes: #8677
Fixes: #8646
Fixes: #8575
Fixes: #8537

## Changelog

N/A since this crate is inaccessible.

### CODE REVIEW

**Comment by prodirus** [comment]
What's the total capacity of the crate? Can it hold up to 60 items (if we roll max 3 times and 20 items each)?

**Comment by prodirus** [comment]
All the tests fail with capacity over 30, ostensibly we'd still be able to go over the cap with the current parameters?

**Comment by Jolly-66** [comment]
> All the tests fail with capacity over 30, ostensibly we'd still be able to go over the cap with the current parameters?

Its likely, I could just make it so the max cap for these crates is 60. Granted, these would never see the light of day so another option is removal, but I think these would be fine to keep as some sort of wonky event item.

**Comment by Jolly-66** [comment]
> Prod

I bumped it up from 1 to 2 with a rounding of 2 since, for some reason, the old lower 1 with a round of 5 produced a few stacks of 0 which I don't get how it happened.

I'll adjust these crates to hold up 60 items.

**Comment by prodirus** [comment]
looks good

**Pull request merged**
